-- SPDX-License-Identifier: LPPL-1.3c
-- Copyright (C) 2026 Christophe Jorssen
-- Author and Current Maintainer: Christophe Jorssen <christophe.jorssen@gmail.com>
-- LPPL maintenance status: maintained
-- This file is part of luafemm. See LICENSE and LICENSES.md for its terms.
-- Development-only importer. The installed package uses the generated Lua data.
local input = arg[1] or "data/femm/matlib.dat"
local output = arg[2] or "tex/generic/luafemm/luafemm-materials-data.lua"
local catalog = arg[3] or "docs/materials-catalog.md"
local revision = "7d9e8ed90772ddb939a3256f976e231bcb5cca97"
local records, folders, used = {}, {}, {}
local current, remaining
local function unquote(s)
    return assert(s:match('^"(.*)"$'), "expected quoted name")
end
local function slug(s)
    return s:lower():gsub("%%", " percent "):gsub("[^a-z0-9]+", "-"):gsub("^%-", ""):gsub("%-$", "")
end
for line in io.lines(input) do
    line = line:gsub("\r", ""):match("^%s*(.-)%s*$")
    if line == "<BeginBlock>" then
        current = { fields = {}, bh = {}, path = table.concat(folders, " / ") }
    elseif line == "<EndBlock>" then
        assert(remaining == 0 and current.name, "incomplete material")
        local id = slug(current.name)
        if used[id] then
            id = id .. "-" .. slug(folders[#folders] or "root")
        end
        assert(not used[id], "duplicate identifier " .. id)
        used[id] = true
        current.id = id
        records[#records + 1] = current
        current = nil
    elseif line == "<EndFolder>" then
        assert(#folders > 0)
        table.remove(folders)
    elseif current and remaining and remaining > 0 then
        local b, h = line:match("^(%S+)%s+(%S+)$")
        current.bh[#current.bh + 1] = { assert(tonumber(b)), assert(tonumber(h)) }
        remaining = remaining - 1
    else
        local key, value = line:match("^<([^>]+)>%s*=%s*(.*)$")
        if key == "FolderName" then
            folders[#folders + 1] = unquote(value)
        elseif current and key == "BlockName" then
            current.name = unquote(value)
        elseif current and key then
            current.fields[key] = assert(tonumber(value), "unknown numeric field " .. key)
            if key == "BHPoints" then
                remaining = current.fields[key]
            end
        end
    end
end
assert(not current and #folders == 0, "incomplete database")
local out = assert(io.open(output, "w"))
out:write(
    "-- SPDX-License-Identifier: LicenseRef-FEMM-AFPL\n",
    "-- Generated by scripts/import-materials.lua; do not edit.\n",
    "-- FEMM copyright David C. Meeker; data converted to Lua on 2026-09-25.\n",
    "-- Upstream data and terms: data/femm/matlib.dat and data/femm/LICENSE.txt.\n",
    "-- Data: FEMM bin/matlib.dat, revision ",
    revision,
    '.\nreturn {revision="',
    revision,
    '",records={\n'
)
for _, r in ipairs(records) do
    out:write(string.format("{id=%q,name=%q,path=%q,fields={", r.id, r.name, r.path))
    local keys = {}
    for k in pairs(r.fields) do
        keys[#keys + 1] = k
    end
    table.sort(keys)
    for _, k in ipairs(keys) do
        out:write(k, "=", string.format("%.17g", r.fields[k]), ",")
    end
    out:write("},bh={")
    for _, p in ipairs(r.bh) do
        out:write(string.format("{%.17g,%.17g},", p[1], p[2]))
    end
    out:write("}},\n")
end
out:write("}}\n")
out:close()
out = assert(io.open(catalog, "w"))
out:write(
    "# FEMM material catalogue\n\n",
    "Generated by `scripts/import-materials.lua` from the preserved `matlib.dat`,\n",
    "revision `",
    revision,
    "`. All ",
    #records,
    " records are retained.\n",
    "FEMM data: see the [upstream terms](../data/femm/LICENSE.txt).\n",
    "Select an identifier with `femm/material=<id>` or `femm/region={material=<id>}`.\n",
    "See [the material guide](materials.md) for static interpretation. J is the\n",
    "default material source in A/m²; `current density=0` overrides it.\n\n",
    "| TikZ identifier | FEMM name | Folder | B–H points | J (A/m²) |\n",
    "| --- | --- | --- | ---: | ---: |\n"
)
for _, r in ipairs(records) do
    out:write(
        string.format(
            "| `%s` | %s | %s | %d | %g |\n",
            r.id,
            r.name,
            r.path,
            #r.bh,
            r.fields.J_re * 1e6
        )
    )
end
out:close()
print(string.format("Imported %d FEMM materials into %s", #records, output))
